name: Run Python Script on Another Repo

on: [push, pull_request]

jobs:
  build:
    runs-on: self-hosted
    
    steps:
    - name: Checkout Current Repo
      uses: actions/checkout@v4
      
    - name: Clone Another Repo
      run: git clone https://github.com/Santhosh26/FortifyCI.git   

    - name: Create .env file
      run: |
        $envPath = "FortifyCI\.env"
        if (Test-Path -Path $envPath) { Remove-Item -Path $envPath }
        echo "SCANCENTRAL_PACKAGE_BT=mvn" >> $envPath
        echo "SCANCENTRAL_PACKAGE_BF=pom.xml" >> $envPath
        echo "SCANCENTRAL_PACKAGE_O=fortifyscanpackage.zip" >> $envPath
        echo "SSC_URL=http://ftfy-sast:8080/ssc" >> $envPath
        echo "SSC_TOKEN=Mzg3ODBjZWQtM2Q3NS00MWJiLWE2ODgtNzc0OGM5NGMzMTcw" >> $envPath
        echo "SSC_SAST_SECRET=secret" >> $envPath
        echo "SSC_APPVERSION_ID=10009" >> $envPath
        echo "SSC_APPNAME=IWA" >> $envPath
        echo "SSC_APPVERSION_NAME=Test" >> $envPath
        echo "SSC_SENSOR_VERSION=23.1" >> $envPath
        echo "FORTIFY_UTILITY_PATH=C:\FortifyBugTrackerUtility-4.11\FortifyBugTrackerUtility-4.11.jar" >> $envPath
        echo "FORTIFY_CONFIG_FILE=C:\FortifyBugTrackerUtility-4.11\SSCToJira.xml" >> $envPath
        echo "SSC_USERNAME=admin" >> $envPath
        echo "SSC_PASSWORD=fh#@673$#byuQWS" >> $envPath
        echo "JIRA_URL=http://localhost:8181/" >> $envPath
        echo "JIRA_USERNAME=admin" >> $envPath
        echo "JIRA_PASSWORD=fh#@673$#byuQWS" >> $envPath
        echo "JIRA_PROJECT_KEY=IWA" >> $envPath
        echo "CRITICAL_ISSUES_LIMIT=99999" >> $envPath
        echo "HIGH_ISSUES_LIMIT=999999" >> $envPath
        echo "MEDIUM_ISSUES_LIMIT=99999" >> $envPath
        echo "LOW_ISSUES_LIMIT=999999" >> $envPath
      shell: pwsh
        
    - name: Run Python Script
      run: python FortifyCI/Fortify-CI.py
