name: Maven CI with Nexus IQ

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn package --file pom.xml
    - name: Nexus IQ Policy Evaluation
      uses: sonatype-nexus-community/iq-github-action@master
      with:
        serverUrl: https://nexusiq.dhl.fortifyhosted.com/
        username: customeradmin-clsu6K
        password: kgRzAEpODC7oWU2l
        applicationId: IWAJ
        stage: Build
        target: ./target/
